[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mini-svg"
version = "1.1.2"
description = "Educational SVG generation library for learning programming with Python."
readme = "README.md"
requires-python = ">=3.11"
license = { file = "LICENSE" }

authors = [
  { name = "hagane" }
]

keywords = ["svg", "education", "graphics", "geometry", "teaching", "learning"]

classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Education",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Operating System :: OS Independent",
  "Topic :: Education",
  "Topic :: Multimedia :: Graphics",
  "Topic :: Software Development :: Libraries"
]

dependencies = []

[project.urls]
Homepage = "https://juanma151.github.io/mini-svg/1.1.2"
Documentation = "https://juanma151.github.io/mini-svg/1.1.2"
Repository = "https://github.com/juanma151/mini-svg"
Issues = "https://github.com/juanma151/mini-svg/issues"


[project.optional-dependencies]
dev = [
  "pytest",
  "ruff",
  "black",
  "mypy",
  "build",
  "twine"
]

docs = [
  "mkdocs",
  "mkdocs-material",
  "mkdocstrings",
  "mkdocstrings-python",
  "mike"
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["mini_svg"]

[tool.ruff]
line-length = 88
target-version = "py311"

[tool.black]
line-length = 88
target-version = ["py311"]

[tool.mypy]
python_version = "3.11"
strict = false

