# -*- coding: utf-8 -*-
# vim: set filetype=dosini fileencoding=utf-8 tabstop=3 shiftwidth=3 noexpandtab :
# SPDX-License-Identifier: MIT
#
# Copyright (c) 2025 hagane
#
# pytest configuration for mini-svg

[pytest]
minversion = 7.0
addopts = -q
testpaths = tests
python_files = test_*.py
python_functions = test_*

