site_name: mini-svg
site_description: Educational SVG generation library for learning programming with Python.
site_url: https://juanma151.github.io/mini-svg/
repo_url: https://github.com/juanma151/mini-svg
repo_name: juanma151/mini-svg

theme:
  name: material
  language: en

  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy
    - content.code.annotate

nav:
  - Home: index.md
  - Levels:
      - Progressive Structure: levels.md
  - API Reference: api.md
  - Utils: utils.md
  - Examples: examples.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - attr_list
  - def_list
  - footnotes

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - ../src
          options:
            show_signature: true
            separate_signature: true
            show_signature_annotations: true
            show_root_heading: true
            show_source: false
            signature_crossrefs: true
            docstring_style: numpy
            docstring_section_style: list
            docstring_options:
              ignore_init_summary: true

docs_dir: docs
site_dir: site

watch:
  - ..


